# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MLService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMLService.proto\x12\x08mccproxy\"8\n\x0ePredictRequest\x12&\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x14.mccproxy.RawFeature\"&\n\x0fPredictResponse\x12\x13\n\x0bis_obsolete\x18\x01 \x03(\x08\";\n\nRawFeature\x12\x15\n\rread_accesses\x18\x01 \x03(\x03\x12\x16\n\x0ewrite_accesses\x18\x02 \x03(\x03\x32M\n\tMLService\x12@\n\x07Predict\x12\x18.mccproxy.PredictRequest\x1a\x19.mccproxy.PredictResponse\"\x00\x42#\n\x0forg.mccproxy.mlB\x0eMLServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MLService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017org.mccproxy.mlB\016MLServiceProtoP\001'
  _globals['_PREDICTREQUEST']._serialized_start=29
  _globals['_PREDICTREQUEST']._serialized_end=85
  _globals['_PREDICTRESPONSE']._serialized_start=87
  _globals['_PREDICTRESPONSE']._serialized_end=125
  _globals['_RAWFEATURE']._serialized_start=127
  _globals['_RAWFEATURE']._serialized_end=186
  _globals['_MLSERVICE']._serialized_start=188
  _globals['_MLSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
